---
kind: pipeline
type: docker
name: default

steps:
  - name: rebuild-cache
    image: docker:git
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ./entrypoint.sh cache --deps="Dockerfile helix.opam"

  - name: test-cache
    image: cache--${DRONE_REPO}:${DRONE_COMMIT_AFTER}
    pull: never
    commands:
      - cat /test.txt

  - name: test-notifications
    image: alpine
    pull: never
    commands:
      - ./entrypoint.sh notify --discord
    environment:
      DISCORD_WEBHOOK_TOKEN:
        from_secret: test_discord_token
      DISCORD_WEBHOOK_ID:
        from_secret: test_discord_id

#  - name: submodules
#    image: alpine/git
#    commands:
#      - git submodule update --init --recursive
#
#  - name: build-vellvm
#    image: cache--${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH}
#    pull: never
#    commands:
#      - opam exec -- make -j 1 vellvm
#
#  - name: compile-helix
#    image: cache--${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH}
#    pull: never
#    commands:
#      - opam exec -- make
#
#  - name: test-helix
#    image: cache--${DRONE_REPO_NAME}:${DRONE_SOURCE_BRANCH}
#    pull: never
#    commands:
#      - opam exec -- make test

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
